# --- Server (ok para Docker)
server.port=8080
server.address=0.0.0.0

# --- PostgreSQL (Supabase - Shared Pooler IPv4)
spring.datasource.url=jdbc:postgresql://aws-0-sa-east-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.ooxzdyhhzrsgxvvkhqmk   # <- copie exatamente como o Supabase mostra pra você
spring.datasource.password=Xe6VJdht6ExyNHw5
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA/Hibernate (para teste)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- Hikari (opcional, seguro para pooler)
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000

# --- Atrás do Nginx (opcional, recomendado)
server.forward-headers-strategy=framework

#Security
spring.security.user.name=kayky
spring.security.user.password=123321
