# Porta e bind (importante para rodar em Docker)
server.port=8080
server.address=0.0.0.0

spring.application.name=Back-API-MTGAudioCar
# Conex�o com o banco Supabase
spring.datasource.url=jdbc:postgresql://db.ooxzdyhhzrsgxvvkhqmk.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Xe6VJdht6ExyNHw5
spring.datasource.hikari.data-source-properties.prepareThreshold=0


# Configura��o JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver

#Security
spring.security.user.name=kayky
spring.security.user.password=123321
