services:
  mtg-back:
    build: .
    image: mtg-back:dev
    container_name: mtg-back
    ports:
      - "8082:8080" # ajuste se usa outra porta no host
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://aws-0-sa-east-1.pooler.supabase.com:5432/postgres?sslmode=require"
      SPRING_DATASOURCE_USERNAME: "postgres.ooxzdyhhzrsgxvvkhqmk"
      SPRING_DATASOURCE_PASSWORD: "COLOQUE_SUA_SENHA_AQUI"
      JAVA_OPTS: "-Djava.net.preferIPv4Stack=true"
    restart: unless-stopped
